=== nutgaard/KPro---Thales/kpro-lib/src/test/java/resources/SettingsXML.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="settings">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="properties" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="key" type="xs:string" />
                            <xs:element name="value" type="xs:string" />
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nutgaard/KPro---Thales/kpro-lib/src/test/java/resources/SettingsXML.xml
<?xml version="1.0" encoding="windows-1252"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<settings
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='SettingsXML.xsd'>
    <properties>
        <key>mail.transport.protocol</key>
        <value>smtps</value>
    </properties>
    <properties>
        <key>mail.store.protocol</key>
        <value>imaps</value>
    </properties>
    <properties>
        <key>mail.smtps.host</key>
        <value>smtp.gmail.com</value>
    </properties>

</settings>
